### ISSUE TITLE
Node-DC-EIS dry run

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/benchmarking#131]
Let us get together to do a dry run of Node-DC-EIS with @uttampawar  and @mhdawson .

Meeting time : 17th August 2017. 11:30 AM PST.

Ref: #123

**Comment by kunalspathak** [comment]
Scheduling to noon PST of 17th August 2017.

**Comment by mhdawson** [comment]
See you then

**Comment by uttampawar** [comment]
See you at noon.

**Comment by mhdawson** [comment]
What are we using to meet ?

**Comment by kunalspathak** [comment]
https://hangouts.google.com/call/vsh2ewzoufb4pe2km5srygx4kiu

**Comment by uttampawar** [comment]
Kunal was going to post hangout link.

**Comment by uttampawar** [comment]
@mhdawson Mike, this still fails to start mongodb server at port 27017 for some reason. I've tested this code and it works perfectly on my local setup. Please help.

**Comment by uttampawar** [comment]
@mhdawson Mike, as I said in my email use of mongo3 fixed the mongodb start issue but now the client driver fails due to following python dependencies,
python v2.x,
module: numpy,
module: requests,
module: eventet, and
module:matplotlib
These are used to communicate with server (http requests) and calculate summary result (using numpy).
Could there be any issue installing these modules on the benchmarking machine?

**Comment by mhdawson** [comment]
This is complete, DC-EIS job is now running.
