### ISSUE TITLE
DC-EIS benchmarking runs hanging

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#153]
```
## SERVER COMMAND ##
  numactl --physcpubind=0,4 /home/iojs/build/workspace/benchmark-footprint-6.x/node/out/Release//node server-cluster
## BEGIN TEST ##

~/build/workspace/benchmark-footprint-6.x/bench/Node-DC-EIS/Node-DC-EIS-cluster ~/build/workspace/benchmark-footprint-6.x/bench
numactl --physcpubind=0,4 /home/iojs/build/workspace/benchmark-footprint-6.x/node/out/Release//node server-cluster
Pre run Footprint in kb : 
## DRIVER COMMAND ##
numactl --physcpubind=2,6 python ./Node-DC-EIS/Node-DC-EIS-client/runspec.py -f ./Node-DC-EIS/Node-DC-EIS-client/config.json -dir /home/iojs/build/workspace/benchmark-footprint-6.x/benchmarking/experimental/benchmarks/results
ERROR: driver failed or killed
npm WARN deprecated mongodb@2.1.16: Please upgrade to 2.2.19 or higher
Caught kill
Killing due to : caught kill
stop: missing job name
Try `stop --help' for more information.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

I've seen the DC-EIS job fail in this manner, when it does it hangs and keeps the machine busy for quite a while.

@uttampawar can you take a look to see what you think might be going on.

**Comment by uttampawar** [comment]
@mhdawson I'll take a look.

**Comment by mhdawson** [comment]
I removed DC-EIS from the 6.x runs as it hung twice in a row.  Will keep an eye on the other versions.

**Comment by uttampawar** [comment]
@mhdawson I just did another run with latest node and it worked okay (at least looks that way). I'll try with 6.x version. But I'm seeing another command not found in the console log. ('bc' not found from cpuParse.sh)

**Comment by uttampawar** [comment]
@mhdawson I did another run with node v6.x and that worked as well.

**Comment by mhdawson** [comment]
It seems to be intermittent, but it happened several times in a row on 6.x tying up the machine so I disabled it there.  If you can continue to look to see if you can find the case where it just hangs I'll keep an eye on the ongoing runs.  If the regular nightlies are ok for the other versions for a few days I'll try turning 6.x back on.

**Comment by mhdawson** [comment]
Hung on master run today: https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-master/722/

If this keeps up may have to remove from all of the main runs, at least until we figure out why its hanging.

**Comment by uttampawar** [comment]
@mhdawson Okay. I'll take another look at the scripts.

**Comment by mhdawson** [comment]
I tried adding 6.x back in but it just hung so I removed it again:

https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-6.x/541/

**Comment by mhdawson** [comment]
```
npm WARN You are using a pre-release version of node and things may not work as expected
../benchmarking/experimental/benchmarks/node-dc-eis/run-dc-eis.sh: line 219: /home/iojs/build/workspace/benchmark-footprint-6.x/benchmarking/experimental/benchmarks/results/temp///20170921-101634/server.out: No such file or directory

## Server no longer running ##
../benchmarking/experimental/benchmarks/node-dc-eis/run-dc-eis.sh: line 221: /home/iojs/build/workspace/benchmark-footprint-6.x/benchmarking/experimental/benchmarks/results/temp/donefile.tmp: No such file or directory
~/build/workspace/benchmark-footprint-6.x/bench
TIMEOUT (600s)
../benchmarking/experimental/benchmarks/node-dc-eis/run-dc-eis.sh: line 178: /home/iojs/build/workspace/benchmark-footprint-6.x/benchmarking/experimental/benchmarks/results/temp/donefile.tmp: No such file or directory
```

It may be that there is some sort of timing issue that 6.x  on that machine seems to fall into.

**Comment by uttampawar** [comment]
@mhdawson Mike, I've modified the build and execution script for a quite a bit. I'm testing it right now. I'll update you with the output so that we can add it again to the queue.

**Comment by uttampawar** [comment]
@mhdawson It looks like starting a mongodb instance is a problem again. I just did one run and I found following error in the log file.
$ cat https://ci.nodejs.org/me/my-views/view/all/job/benchmark-node-dc-eis/ws/benchmarking/experimental/benchmarks/results/20170922-170222/node-dc-eis.log

## STARTING MONGODB ##
 /home/iojs/acmeair/mongo3/mongodb.sh start 27017
~/acmeair/mongo3 ~/build/workspace/benchmark-node-dc-eis/bench
/home/iojs/acmeair/mongo3/mongodb.sh: line 10:  1859 Terminated              sleep 2

Since, I don't have access to the machine, I can't examine what is in '/home/iojs/acmeair/mongo3/mongodb.sh script. Can you help, please?

a) Do a node build
b) Clone bench
c) Clone benchmarking.git
d) Start the run
e) Display Final results
    - Throughput
    - Latency
    - Pre footprint
    - Post footprint

I've changed dc-eis scripts with following rough understanding of the execution flow....
1) Pre work
     - Collect following logs,
        - results/temp/score_summary.txt
        - results/temp/server_cpu.txt
        - results/temp/footprint_output.log
        - results/temp/<TEST_NAME.log> file 
        - Set Archive directory results/<current_date>

2) start the database (if needed, in this case yes)
    - wait till it starts okay. 
    - Exit the run if this fails. Default wait it 60 seconds. 
3) start the node application server 
    - wait till it started okay
    - Exit the run if this fails. Default wait it 60 seconds. 
4) Collect memory foot print before the actual run
  - pre=getFootprint() call
5) Start the client program in the background
6) Collect CPU stats during the execution
7) Collect memory foot print immediately after the run
    - post=getFootprint() call
8) Record end time and calculate elapsed time
9) Start timer to make sure everything is finished and stopped (currently 100sec for dc-eis)
10) stop client (if needed)
11) stop node application server
12) stop mongodb server (if needed)
13) Archive files 
      - Move files from benchmarking/experimental/benchmarks/results/temp directory to the benchmarking/experimental/benchmarks/results/<current_date> directory 
14) Delete benchmarking/experimental/benchmarks/results/temp directory

Any feedback would be appreciated.

**Comment by gareth-ellis** [comment]
Unless its been changed, the mongodb.sh, if you pass it "start" it will create a new db directory, then start mongodb and check the log until it reports mongodb has started, then will exit.

If its getting killed at sleep 2, that means that the job has carried on, and mongodb never started.
I believe the script there is almost the same as the one in experimental/benchmarks/acmeair/mongodb.sh, the reason we use a different script for the daily runs is we wanted to keep a static version of mongodb, so this was unzipped on the benchmarking machine - rather than automatically installing via package manager and getting versions at random. The one in experimental/benchmarks/acmeair/mongodb.sh is for use with the docker image, which would compare two acme air results; since we are collecting both data points at the same time, its ok if we change mongo versions over time in the docker image.

The one stored on the benchmark machine will run ./mongod rather than using one that (shouldn't be) globally available

One more thing ive noticed, that could well be a problem, is you want to use a database name called "export DB_URL="mongodb://127.0.0.1:${MONGODB_PORT}/node-dc-eis-db""

The original script only used the dbpath of "database" - I cant find right now if dbpath is the same as the database name you specify in the url - e.g. we start  mongodb for the "database" database but we actually try and connect to the node-dc-eis-db. It may be the dbpath can be whatever you want and you then can connect to the db you wish. 

There is a log file in the mongodb directory where it would be useful to look. you could also copy it over to the workspace at the end of the run, that way you can see if theres errors there.

I note the script has been changed from acmeair to not do a pkill on mongod - it may be worth adding those back - the "kill_bkg_processes" function is only run when things go wrong, and the point was to clean up the machine as best as possible. It currently contains a stop command, which will work if mongodb is in a good state, however since we only run this when things have gone wrong, making assumptions that the stop will work may not be best.

If @mhdawson can supply the /home/iojs/acmeair/mongo3/mongodb.sh file, then we can review it and potentially we may need to allow adding in a "dbpath" parameter to allow different dbs to be used for acmeair and node dc-eis (though they get cleared each time we start mongo, so that may not be strictly necessary...)

**Comment by mhdawson** [comment]
The contents of the mongodb.sh script are as follow:

iojs@nodejsb1:~/acmeair/mongo3$ cat mongodb.sh
#!/bin/bash
if [ -z "$1" ]; then
echo "Must pass in start, stop or status"
exit
fi
DIR=`dirname $0`
CURRENT_DIR=`cd $DIR;pwd`
pushd $CURRENT_DIR

case $1 in
start)
rm -rf database
mkdir database
rm mongodb.out
./mongod --dbpath database >> mongodb.out 2>&1 &
while [ `grep -c "db version v3.0.3" mongodb.out` -lt 1 ]
do
sleep 2
done
echo "mongo started at `date`"
;;
stop)

./mongod --dbpath database  --shutdown
rm -rf database
;;
status)
ps -ef|grep mongod|grep -v grep
;;
esac
popd



Can you raise an issue in the repo and @cc Gareth as he wrote those 
original scripts and maybe he can help

In the end you don't need to re-use that script if its not working in some 
cases:



Regards,

Michael (M.H.) Dawson
Runtime Technologies Node.js Technical Lead
Software Developer and Master Inventor


Phone: 1-613-356-5484 | Phone: 1-343-882-2473
E-mail: Michael_Dawson@ca.ibm.com
Find me on:   


3755 Riverside Drive
Ottawa, ON K1V 1B8
Canada

**Comment by uttampawar** [comment]
@mhdawson I saw that node-dc-eis job is running but it's being using main repo instead of mine. Can you fix that and re-start please?

**Comment by mhdawson** [comment]
I killed the job.  Unfortunately I have other priorities for the next few days so I may not be able to update the jobs until later in the week.

**Comment by mhdawson** [comment]
@uttampawar where is the PR ? I assume you had submitted a PR with the changes and I would point the job to the branch for that PR to validate before landing.

**Comment by uttampawar** [comment]
@mhdawson Submitted a new PR with appropriate changes. My testing of these changes didn't reveal any "hanging" issues. It shows some conflict with mainline. May be I should resolve them first?

**Comment by mhdawson** [comment]
I believe this is now resolved, closing.
