### ISSUE TITLE
Audit benchmarks on v6.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/benchmarking#162]
The delta between v6.x and master has gotten non trivial. I think it would make sense to Audit the 6.x branch and see what needs to be done to get things up to date

**Comment by joyeecheung** [comment]
Are you talking about the benchmarks on https://benchmarking.nodejs.org/  or the core micro-benchmarks?

**Comment by mhdawson** [comment]
Agreed, not really sure what you are asking for.  Can you add some more detail.

**Comment by MylesBorins** [comment]
I was referring to the benchmark folder in the 6.x release line. The tooling is quite out of date

**Comment by joyeecheung** [comment]
The benchmark tooling in the core was rewritten during v6.x as semver-major so it is not available in v6.x (https://github.com/nodejs/node/pull/7094), therefore almost every update in the benchmark folder does not apply to v6.x.

I think we should skip backporting benchmark commits, and ask people updating benchmarks in their PR to split those changes into separate commits?

**Comment by joyeecheung** [comment]
Uh...wait, if you are talking about bringing the existing benchmark folder in v6.x branch up-to-date, then yes, it needs to be audited because there could probably be some commits that depend on the new tooling landed. Although...do we still run the benchmarks in the v6.x branch? Is it necessary? If we are comparing the performance differnce between v6.x and other later release lines, since the tooling in v6.x does not generate the same output as others, we probably can't use them as-is anyway.
