### ISSUE TITLE
Easy acmeair benchmarking setup

### ISSUE THREAD

**Issue by mscdex** [nodejs/benchmarking#47]
Is there a VM image, container, or something similar that I can use to easily test local performance-related changes (for the acmeair benchmarks)?

**Comment by mhdawson** [comment]
There is nothing like that right now. The scripts are in the benchmarking repo but the other components are only on the benchmarking machine as I was not sure about licences etc.  @gareth-ellis would it be possible to put together a step by help of how to get components/install/run and then we could use that to see if we can provide a pre-bundled package or something like that.

**Comment by gareth-ellis** [comment]
I can look at putting together a list of steps to get the benchmark to work, however what would be the ideal solution? Some sort of docker image? Or just a script that can collect the artefacts and run?

Getting some performance tests run when potentially performance risky changes are going in would be a good step and would be easier than investigating a wide range of change sets in retrospect

What will be important for testing a change would be to do a few runs of node with and without the change so that you can be sure that you're getting reliable numbers as relying on data either collected on another machine or on a build a number of changes since will not really tell you much.

**Comment by mscdex** [comment]
Docker or similar image would be ideal I think. Less headache/work the better :-)

**Comment by gareth-ellis** [comment]
OK, I've not done much with docker, but will take a look and report back!

**Comment by gareth-ellis** [comment]
@mscdex 

Sorry for the delay.

I've put together a dockerfile which will start up a ubuntu image, install dependencies, copy over an Assets.zip (which contains a patched version of apache jmeter, and a copy of acmeair). It will also put over two copies of node - a baseline & a build to test. 
Ideal situation would be that you could generate a baseline which is head, and a build which is head + the change being tested. This sort of thing would be good as part of the CI when we are looking at potentially risky changes.
The dockerfile then checks out the node benchmarking repo (currently my fork - but will put in a PR soon to merge in the changes) and then runs three iterations of each "interleaved" - where we do build, baseline, build, baseline, build, baseline. This should hopefully mean any machine noise would affect both builds the same - I want to do a few different tests to see how reliable docker images are for performance. we then report the comparison - where above 100% is good and below is bad.

Ideally maintaining a static version of Jmeter & acmeair would be good - which is why i opted to copying over a zip file, rather than downloading / checking out + then patching jmeter (required to run acmeair).

So currently requirements are:

- Assets.zip file - can provide
- Dockerfile
- Two copies of Node  - currently named node_undertest & node_baseline

That's about it.

Let me know what you think about this proposal and I can make changes / give you a copy to try

**Comment by gareth-ellis** [comment]
So, now that we've got this it would be good to try getting it in a state where it's easy to launch a run compare - perhaps if we have any performance risky changes due to come in?

@mscdex , what would be a good way of moving forward so we can start using this?

**Comment by gareth-ellis** [comment]
Will close this, the dockerfile is still in the benchmarking repo, if there's anything else we need to do on that, let us know @mscdex
